### ISSUE TITLE
Switch license to Modified BSD

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Diff#106]
This is a proposal to switch from GNU GPL v2+ to [Modified-BSD](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)).

Modified-BSD is currently the standard license to use for WMDE projects that we expect to be reused by third parties. Diff is also the most reused of the WMDE libraries on GitHub and [third parties have requested such a license change](https://github.com/wmde/Diff/issues/88).

All authors of code present in the latest version of Diff need to agree to this change. Please indicate agreement or disagreement with a comment below if you are one of the authors.

Authors as of b9a44776bc45997d1f54f07e54615fa3b81f7de8 (via `git shortlog -sn`):

* [x] jeroendedauw
* [x] @thiemowmde
* [x] @mariushoch 
* [x] Denny Vrandecic
* [x] ~~John Erling Blad~~ - no surviving code
* [x] @manicki
* [x] @addshore
* [x] ~~Daniel Werner~~ - no surviving code
* [x] @tobijat
* [x] @brightbyte
* [x] ~~Siebrand Mazeland~~ - no surviving code
* [x] ~~@reedy~~ - no surviving code
* [x] ~~Luis Cordova~~ - no surviving code
* [x] @Ladsgroup 
* [x] @hashar
* [x] ~~Chad Horohoe~~ - no surviving code
* [x] Eddie Diaz @speedzz
* [x] ~~Jan Zerebecki~~ - no surviving code
* [x] ~~Jens Ohlig~~ - no surviving code
* [x] ~~Katie Filbert~~ - no surviving code
* [x] @mlazowik

**Comment by vrandezo** [comment]
I agree. Thanks for doing this.

**Comment by addshore** [comment]
I also agree

**Comment by tobijat** [comment]
Agree.

**Comment by hashar** [comment]
I only have a dummy fix fc8bea20f43bf589f180dacb69e3d1b3fe151d66 . +1 yes

**Comment by manicki** [comment]
i agree

**Comment by thiemowmde** [comment]
From a legal perspective, can anyone explain (or link to a blog post) what the relevant (for me as a contributor) differences between the two licenses are?

**Comment by speedzz** [comment]
I agree

**Comment by Ladsgroup** [comment]
I agree

**Comment by mariushoch** [comment]
I also agree

**Comment by thiemowmde** [comment]
I agree

**Comment by brightbyte** [comment]
I agree

**Comment by JeroenDeDauw** [comment]
Awesome. Thank you everyone. I'll put up a PR to switch over to the new license tomorrow.
