### ISSUE TITLE
MapDiff and ListDiff still referenced

### ISSUE THREAD

**Issue by reedy** [wmde/Diff#122]
https://github.com/wmde/Diff/blob/e12d4b0f8c1d26263faf6e70f4771f8f2b3a7246/src/DiffOp/DiffOp.php#L14

But

https://github.com/wmde/Diff/blob/89bbd224a9ad6cc6cb8e01263ae5add2564e7cf0/RELEASE-NOTES.md#L30

**Comment by JeroenDeDauw** [comment]
Here you go https://github.com/wmde/Diff/pull/123
