### ISSUE TITLE
[Action required] actions/cache v1-v2 is closing down

### ISSUE THREAD

**Issue by reedy** [wmde/Diff#147]

**Comment by manicki** [comment]
I am not an expert but is this repository affected? Two workflows here use either v3 or v4. Surely should make them both use v4 but the closing down of v1 and v2 shouldn't break anything? Or is it about some "dependency of the dependency" situation I cannot immediately notice?

**Comment by reedy** [comment]
Not 100% sure either at this point... Looks fine indeed
