### ISSUE TITLE
Plan to have a concrete documentation ?

### ISSUE THREAD

**Issue by IvanDelsinne** [wmde/Diff#82]
Do you plan to write/generate any comprehensive documentation for, at least, the API (and maybe some more detailed examples) ?

**Comment by JeroenDeDauw** [comment]
There is no plan for this.

API wise I'm not sure what would be helpful beyond what is already in the README. There are tools such as doxygen that allow you to create HTML documentation from the source, though personally I've always found this kind of documentation inferior to looking at the actual code. Is this what you had in mind? 

What examples are you missing at the moment? Definitely feel free to create a pull request that adds some new ones.
