### ISSUE TITLE
Re-license to LGPL, MIT, BSD or similar?

### ISSUE THREAD

**Issue by motin** [wmde/Diff#88]
I am a long-time open source contributor and promoter, but the use of GPL is making it impossible for me to use or contribute to its development since not only do I do open source, I also sell my time as a programmer for other companies, and in those projects GPL is not an option.

Will you consider re-licensing this to LGPL, MIT, BSD or similar?

**Comment by JeroenDeDauw** [comment]
I'd be fine with this though do not have time to look into it. At the moment we have, as far as I know, no clear policies or guidelines for this at WMDE

**Comment by okyselov** [comment]
It's a pity. I also need relicensing and currently I forced to avoid use this library.

**Comment by JeroenDeDauw** [comment]
I'll investigate what can be done

**Comment by okyselov** [comment]
@JeroenDeDauw The GPL does not permit incorporating your library into proprietary programs. This is problem, which can be solved by relicensing to LGPL.

**Comment by JeroenDeDauw** [comment]
Thanks for explaining.

If we change the license it will be to Modified BSD. Since the copyright lies with the individual contributors, we'll need to get approval from all of them though.

**Comment by JeroenDeDauw** [comment]
This is now tracked by https://github.com/wmde/Diff/issues/106

**Comment by JeroenDeDauw** [comment]
@okyselov @motin version 3.2.0 was just released and it is licensed under modified BSD. Enjoy! :)
